apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-frontend-deployment
  name: nodejs-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-frontend-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: nodejs-frontend-deployment
    spec:
      initContainers:
        - name: init-envjs
          image: busybox:1.28
          command:
          - 'sh'
          - '-c'
          - 'echo "window.productApiUrl = \"$VITE_PRODUCT_API_URL\"; window.userApiUrl = \"$VITE_USER_API_URL\";" > /tmp/init-envjs/app-config.js'
          env:
            - name: VITE_PRODUCT_API_URL
              valueFrom:
                configMapKeyRef:
                  key: VITE_PRODUCT_API_URL
                  name: frontend-config
            - name: VITE_USER_API_URL
              valueFrom:
                configMapKeyRef:
                  key: VITE_USER_API_URL
                  name: frontend-config
          volumeMounts:
            - name: app-config
              mountPath: /tmp/init-envjs
      containers:
        - image: sg6web/nodejs-k8s-test-app-frontend
          name: nodejs-k8s-test-app-frontend
          imagePullPolicy: "Always"
          env:
            - name: VITE_PRODUCT_API_URL
              valueFrom:
                configMapKeyRef:
                  key: VITE_PRODUCT_API_URL
                  name: frontend-config
            - name: VITE_USER_API_URL
              valueFrom:
                configMapKeyRef:
                  key: VITE_USER_API_URL
                  name: frontend-config
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
          volumeMounts:
            - name: app-config
              mountPath: /usr/share/nginx/html/public/app-config
      terminationGracePeriodSeconds: 30
      volumes:
        - name: app-config
          emptyDir: { }

