apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-frontend-service-nodeport
  name: nodejs-frontend-service-nodeport
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30099
  selector:
    app: nodejs-frontend-deployment
  type: NodePort
