apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-user-service-nodeport
  name: nodejs-user-service-nodeport
spec:
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30100
  selector:
    app: nodejs-user-service-deployment
  type: NodePort
