apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-debugger
  name: busybox-debugger
spec:
  containers:
    - image: busybox
      name: busybox-debugger
      resources:
        limits:
          cpu: "150m"
          memory: "200Mi"
        requests:
          cpu: "50m"
          memory: "50Mi"
  restartPolicy: Always
