apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-nodeport
  name: nodejs-nodeport
spec:
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30008
  selector:
    app: nodejs-app
  type: NodePort
